# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# export L first so that it can be used throughout the configuration
export L="$HOME/.local"

#
# alphabetized variable exports
#
export C_INCLUDE_PATH=/opt/local/include

export CHROME_EXECUTABLE=/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser

# point google cloud sdk to the right python
export CLOUDSDK_PYTHON=/opt/local/bin/python3.11

export EDITOR=$L/bin/nvim

export HDF5_DIR=/opt/local

export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk17/Contents/Home

export GOPATH="$L/var/go"
export GOBIN="$GOPATH/bin"

export GPG_AGENT=/Applications/MacPorts/pinentry-mac.app/Contents/MacOS/pinentry-mac
export GPG_TTY=`tty`

export LC_ALL=en_US.UTF-8 

export LIBRARY_PATH=/opt/local/include

export NPM_PACKAGES="$L/opt/npm"

export TFENV_ARCH=arm
export TFENV_CONFIG_DIR=~/.tfenv

export VIRTUALENV_DIR="$L/share/virtualenvs"

export ZD=${ZDOTDIR}


#
# expport MANPATH last since it requires other variable definitions, above
#
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"


#
# source additional files for variables
#
source ${ZDOTDIR}/secrets.d/*

