# Source Prezto.
if [[ -s "$HOME/src/github.com/wryfi/prezto/init.zsh" ]]; then
  source "$HOME/src/github.com/wryfi/prezto/init.zsh"
fi

fpath=(~/.local/etc/zsh/bin "${fpath[@]}")
autoload -U compinit && compinit

precmd () {print -Pn "\e]0;%~\a"};


# define a function to detect aliases or shell functions
is_alias_or_function() {
  if [[ -n "$(alias $1 2>/dev/null)" ]]; then
    echo alias
  elif [[ "$(function $1 2>/dev/null)" ]]; then
    echo "$1 is a function"
  else
    echo function
  fi
}

# unalias ls & lt as needed

for al in {l,la,lc,ll,lk,lm,lr,ls,lt,lu,sl}; do
  if [[ $(is_alias_or_function $al) = "alias" ]]; then
    unalias $al
  fi
done


# source additional rc files first so they don't shadow our fns/aliases

if [[ -d "${ZDOTDIR}/rc.d" ]]; then
  for file in $(find "${ZDOTDIR}/rc.d" -not -type d | sort); do . "$file"; done
fi



# Aliases

alias back="{ git checkout git rev-list -1 --before=\"$1\" master; };"
alias bat="bat --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo Nord || echo GitHub)"

#alias grep='rg'

alias kl='kubectl'

alias l='eza --icons=auto --group-directories-first'
alias ls='l -1'
alias ll='l -l'
alias la='l -Al --time-style long-iso -g'
alias lk='la --sort=size'
alias lt='la --sort=age --reverse'
alias lg='lt --git --git-repos'
alias lrg='la | rg -i'

alias nv="$(which nvim)"
alias nv2="$(which nvim)"
alias nv4="$(which nvim) -u ~/.vimrc_4space"
alias vim="$(which nvim)"

alias salt-push='git push && ssh admin.fre.wryfi.net "cd /srv/sdm && sudo -E git up"'

# Functions
cl () {
  pushd ~/.local/$1
}

create_postgres_db() {
  echo "database name: "
  Read db_name
  echo "database owner: "
  read db_owner
  sudo -u postgres createdb --locale=en_US.UTF-8 -E utf-8 -O $db_owner -T template0 $db_name
}

doc() {
  infile="${1}"
  outfile="${2}"
  if [[ -z $infile || -z $outfile ]]; then
    echo "must provide infile and outfile"
    return 1
  fi
  pandoc -f markdown -t docx --lua-filter=$HOME/.local/etc/pandoc/pagebreak.lua -o $outfile $infile
}

ec2() {
  local profile="$1"
  local tag="$2"
  local values="$3"
  aws ec2 --profile "${profile}" describe-instances --filters "Name=tag:${tag},Values=${values}" \
    | jq '[.Reservations[] | {instanceId: .Instances[0].InstanceId, ip: .Instances[0].PrivateIpAddress}]'
}

envload() {
  while IFS='=' read -r key value; do
    [[ $key =~ ^#.*$ || -z $key ]] && continue
    printf -v "$key" '%s' "$value" && export "$key"
  done < ${1:-.env}
}

envunload() {
  while IFS='=' read -r key value; do
    [[ $key =~ ^#.*$ || -z $key ]] && continue
    unset "$key"
  done < ${1:-.env}
  source $ZD/.zshrc
}

gcd() {
  local dir="$HOME/src"
  if [[ "$1" = "h" ]]; then dir="$dir/github.com/wryfi"; fi
  if [[ "$1" = "l" ]]; then dir="$dir/gitlab.com/wryfi"; fi
  if [[ "$1" = "z" ]]; then dir="$dir/local"; fi
  if [[ "$2" != "" ]]; then
    if [[ -d "$dir/$2" ]]; then
      pushd "$dir/$2"
      return
    fi
  elif [[ "$1" =~ '^[hlz]$' ]]; then
    pushd $(FZF_DEFAULT_COMMAND="fd --type d -d 1 . $dir" fzf)
    return
  fi
  pushd $(FZF_DEFAULT_COMMAND="fd --type d -d 3 . ~/src" fzf)
}

hgrep () {
  fc -Dlim "*$@*" 1
}

known-host-rm() {
  [ -n "$1" ] && [[ $1 =~ ^[0-9]+$ ]] && /usr/bin/sed -i '' "${1}d" ~/.ssh/known_hosts
}

ltr() {
  eza -T -L ${2:-3} ${@:1}
}

mkcd() {
  mkdir -p $1 && cd $_
}

mkvirtualenv () {
    python -m venv ${VIRTUALENV_DIR}/$1
    echo "created ${VIRTUALENV_DIR}/$1"
    . ${VIRTUALENV_DIR}/$1/bin/activate
}

odt() {
  infile="${1}"
  outfile="${2}"
  if [[ -z $infile || -z $outfile ]]; then
    echo "must provide infile and outfile"
    return 1
  fi
  pandoc -f markdown -t odt --lua-filter=$HOME/.local/etc/pandoc/pagebreak.lua -o $outfile $infile
}

pdf() {
  infile="${1}"
  outfile="${2}"
  if [[ -z $infile || -z $outfile ]]; then
    echo "must provide infile and outfile"
    return 1
  fi
  pandoc -f markdown -t pdf --pdf-engine=xelatex -V geometry=margin=1in -V colorlinks -V mainfont=Lato -H  ~/.local/etc/pandoc/customize.tex -o $outfile $infile
  echo "generated pdf: $outfile"
}

repo-sync() {
  rsync -av --exclude=.git --exclude=.gitignore --exclude=.idea $1 $2
}

rmvirtualenv () {
  if [[ $VIRTUAL_ENV = "${VIRTUALENV_DIR}/$1" ]]; then deactivate; fi
  rm -rf ${VIRTUALENV_DIR}/$1
}

watchcmd() {
  watched="${1}"
  shift
  command=("$@")
  echo "watching ${watched} with command '${command}' ... "
  fswatch -0 "${watched}" --event Created --event Updated | xargs -0 -I{} ${command[*]}
}

watchpdf() {
  infile="${1}"
  outfile="${2}"
  fswatch -o "$infile" -0 | xargs -0 -n1 -I{} pandoc -f markdown -t pdf \
  --pdf-engine=xelatex -H ~/.local/etc/pandoc/customize.tex -o $outfile $infile
}

workon() {
    . ${VIRTUALENV_DIR}/$1/bin/activate
}

zv () {
  nvim $ZDOTDIR/$1
}

